# Generated by Django 5.1.3 on 2024-11-13 12:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='refillrequest',
            name='user',
        ),
    ]
